# .github/workflows/deploy.yml
name: Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm ci
      - run: npx hardhat test
      - run: npx hardhat deploy-all --network sepolia
        env:
          SEPOLIA_RPC: ${{ secrets.SEPOLIA_RPC }}
          PRIVATE_KEY: ${{ secrets.DEPLOYER_KEY }}